sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 050228
  redis:
    host: 192.168.118.132
    port: 6379
  wechat:
    appid: wx567ba7c76ff3bfbc
    secret: d493641e2425a280f4fca19ad64be326
    notifyUrl: https://39dc8d3d.r9.cpolar.cn///notify/paySuccess
    refundNotifyUrl: https://39dc8d3d.r9.cpolar.cn///notify/refundSuccess